import torch and check torch and cuda

In [1]:
import torch

In [2]:
print(torch.__version__)

1.1.0


In [3]:
torch.cuda.is_available()

True

In [4]:
torch.version.cuda

'10.0.130'

create tensor and move it to gpu

In [5]:
t = torch.tensor([1,2,3])
t

tensor([1, 2, 3])

In [6]:
t = t.cuda()
t

tensor([1, 2, 3], device='cuda:0')

tensor's rank, axis and shape 

In [7]:
d =([1,2,3],
    [4,5,6],
    [7,8,9])
print(d)
print(d[0])

([1, 2, 3], [4, 5, 6], [7, 8, 9])
[1, 2, 3]


In [8]:
t = torch.tensor(d)
print(t)
type(t)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


torch.Tensor

In [9]:
t.shape

torch.Size([3, 3])

In [10]:
print(t.reshape(1,9))

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])


tensor data initialization with numpy

In [12]:
import numpy as np

In [13]:
d = np.array([1,2,3])

In [14]:
t = torch.tensor(d)
t

tensor([1, 2, 3])

In [15]:
t.device

device(type='cpu')

In [16]:
t1 = t.cuda()
t1.device

device(type='cuda', index=0)

Tensor Flatten

In [17]:
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

In [20]:
t = torch.stack((t1,t2,t3))
t.shape

torch.Size([3, 4, 4])

In [21]:
t = t.reshape(3,1,4,4,)
t.shape

torch.Size([3, 1, 4, 4])

In [28]:
t.flatten()

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [29]:
t.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [30]:
t.flatten(start_dim=1).shape

torch.Size([3, 16])